### ISSUE TITLE
Naming of work

### ISSUE THREAD

**Issue by martinthomson** [w3c/vc-jws-2020#31]
The title of the current document ("JSON Web Signature 2020") is potentially misleading.  It implies a revision of the JWS specification rather than what it actually appears to be.  If this were a revision, as opposed to a set of algorithm identifiers and a profile that uses those, then that would be the domain of the IETF[^1].

The titles used on the repository are clearer perhaps, but if I might suggest something like "Profile of JSON Web Signatures for Verifiable Credentials" or similar.

This probably extends to the identifiers chosen.  Perhaps "vc-jws-2020" works[^2].

[^1]: I'll note that the idea of using a year to identify a profile in this manner has been discussed in the IETF, to a generally unfavourable response (or at least that is my interpretation of the feedback received).

[^2]: or maybe 2023?

**Comment by OR13** [comment]
> Profile of JSON Web Signatures for Verifiable Credentials

Good suggestion, I agree with the title being misleading.

Another option would be "JSON Web Signatures for Data Integrity Proofs"

**Comment by mprorock** [comment]
I am a fan of "JSON Web Signatures for Data Integrity Proofs" or "Data Integrity Proofs with JSON Web Signatures"

**Comment by Sakurann** [comment]
> Profile of JSON Web Signatures for Verifiable Credentials

this is misleading in my opinion. The naming should reflect that this is a crypto suite to be used with Data Integrity.

So something like “JSON Web Signature Suite for Data Integrity” would be preferable.

**Comment by brianorwhatever** [comment]
> Another option would be "JSON Web Signatures for Data Integrity Proofs"

+1 to this option

**Comment by peacekeeper** [comment]
Does it even need a special human-readable name? Why not just call them all consistently:
- JsonWebSignature2020 cryptosuite
- Ed25519Signature2018 cryptosuite
- Ed25519Signature2020 cryptosuite
- DataIntegrityProof cryptosuite

Or something other than "cryptosuite". Anyway, just an idea, I also like the names proposed above.

**Comment by OR13** [comment]
@peacekeeper I think it is a mistake to name the spec exactly the same as the RDF type, but certainly all the types should align with each other.

I have proposed the name with the most consensus on this thread here: https://github.com/w3c/vc-jws-2020/pull/32

**Comment by brentzundel** [comment]
PR #32 has been merged. Can this be closed?
