### ISSUE TITLE
Rename to `di-jws-2020` ?

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jws-2020#5]
Once we have other data integrity suites in the vc wg, we may want to align their names.

**Comment by iherman** [comment]
At present (except for the WG home page, which we inherited from ancient times) all repositories have a similar pattern: vc-XXX. We may want to stick to that, though.

**Comment by mprorock** [comment]
my preference would be to drop 2020 - open to conversation of `vc-jws`, `vc-di-jws`, or `di-jws` as options for better naming
