### ISSUE TITLE
`CG-Final` required

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jws-2020#6]
Cant really call this done until the final CG draft points to `latestVersion: "https://www.w3.org...`

**Comment by OR13** [comment]
WIP here: https://github.com/w3c-ccg/lds-jws2020/pull/98

**Comment by OR13** [comment]
@iherman how can we get publishing setup for this first editors draft? I would like to point the CG final to this repo asap.

**Comment by OR13** [comment]
Related:

> This version:
> https://www.w3.org/community/reports/credentials/CG-FINAL-data-integrity-20220720/
> Latest published version:
> https://www.w3.org/2022/07/data-integrity-20220720/
> Latest editor's draft:
> https://w3c.github.io/data-integrity-spec/

**Comment by iherman** [comment]
> @iherman how can we get publishing setup for this first editors draft? I would like to point the CG final to this repo asap.

I am not sure I understand your question, @OR13.

**Comment by OR13** [comment]
@iherman 

Its nearly done, see:

https://github.com/w3c/cg-reports/pull/2

Once the links are fixed, I will be able to link EDs in this repo to the final CG report.

I am hoping to setup ED publishing in this repo as the next step.
