### ISSUE TITLE
Unable to transfer issues from ccg

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jws-2020#8]
https://github.com/w3c-ccg/lds-jws2020/issues

See: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

> To transfer an open issue to another repository, you must have write access to the repository the issue is in and the repository you're transferring the issue to. For more information, see "[Repository roles for an organization](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization)."

cc @iherman

**Comment by OR13** [comment]
hmm perhaps I was wrong and you can't transfer issues across orgs.

**Comment by OR13** [comment]
Seems I will need to transfer the repo to the w3c ccg to move the issues.

Then transfer the repo back to the w3c ccg and archive it.

**Comment by iherman** [comment]
@OR13 I would need some extra rights on the w3c-ccg version to do the move. At present, it seems I am just a lambda user and not access to the 'Setting' tabs. I presume I must have at least the 'Maintain' right (I am admin on the w3c side, so to problem there).

**Comment by OR13** [comment]
Yes, I have made you an admin, I am not able to transfer the repo to w3c currently, but you should now be able to.

**Comment by OR13** [comment]
once its transferred if you make me an admin I should be able to complete the process.

**Comment by OR13** [comment]
done
